### ISSUE TITLE
MVC Categoria

### ISSUE THREAD

**Issue by LuizMoratelli** [HugoHoffmann/desWebI-laravel#3]
- [x] Views:
  - [x] listagem
  - [x] inclusão
  - [x] alteração
- [x] Ações:
  - [x] incluir
  - [x] listar
  - [x] alterar
  - [x] remover
- [x] Rotas

**Comment by HugoHoffmann** [comment]
## To fix/improve:
- [x] Poder incluir novo cliente 
- [x] Poder excluir cliente 
- [x] Mensagem de falha caso não consiga efetuar ação (atualizar/excluir)
  - [x] Não pode excluir se possuir tabelas que referenciem-a
  - [x] Deixar o input, na view de alterar, disabled se possuir tabelas referenciando-a e mostrar mensagem.

**Comment by HugoHoffmann** [comment]
## To fix/improve:
- [ ] Poder incluir novo cliente 
- [ ] Poder excluir cliente 
- [ ] Mensagem de falha caso não consiga efetuar ação (atualizar/excluir)
  - [ ] Não pode excluir se possuir tabelas que referenciem-a
  - [ ] Deixar o input, na view de alterar, disabled se possuir tabelas referenciando-a e mostrar mensagem.

**Comment by HugoHoffmann** [comment]
## To fix/improve:
- [x] Poder incluir novo cliente 
- [x] Poder excluir cliente 
- [x] Mensagem de falha caso não consiga efetuar ação (atualizar/excluir)
  - [x] Não pode excluir se possuir tabelas que referenciem-a
  - [x] Deixar o input, na view de alterar, disabled se possuir tabelas referenciando-a e mostrar mensagem.

**Comment by LuizMoratelli** [comment]
- [ ] Implementar visualização/alteração/inclusão da imagem (picture)
