### ISSUE TITLE
MVC Ordem

### ISSUE THREAD

**Issue by LuizMoratelli** [HugoHoffmann/desWebI-laravel#4]
- [x] Views:
  - [x] listagem
  - [x] inclusão
  - [x] alteração
- [x] Ações:
  - [x] incluir
  - [x] listar
  - [x] alterar
  - [x] remover
- [x] Rotas

**Comment by HugoHoffmann** [comment]
- [x] Correção Controller

- [x] Adicionar demais campos em inclusão e alteração

**Comment by HugoHoffmann** [comment]
- [x] Adapção controller
